### ISSUE TITLE
Avoid using innerHTML

### ISSUE THREAD

**Issue by vandijkstef** [maybuzz/web-app-from-scratch-18-19#3]
https://github.com/maybuzz/web-app-from-scratch-18-19/blob/7bddc7cdac82bd7b3f01ac26ca9e744a42fe7446/week1/js/app.js#L19

**Comment by maybuzz** [comment]
I thought we we're supposed to use innerHTML. It was given as a resource in the assignment file.

I used textContent before I started using innerHTML, see [this commit](https://github.com/maybuzz/web-app-from-scratch-18-19/commit/03ecceb4dfeb94835df86156bc87ccd096304f62) (week1/js/app.js:15) If this is okay, I'll put it back.

**Comment by maanlamp** [comment]
@maybuzz I think what he means is: use `document.createElement` and other builtin methods instead of `innerHTML`. Consider using a simple template engine :)

**Comment by vandijkstef** [comment]
@maanlamp Indeed.
@maybuzz I dislike the innerHTML pattern and prefer to use innerText (disables HTML parsing), which forces you to use create/append pattern. Though I had convo about this with Joost afterwards, and innerHTML could have it's benefits. It'll be discussed during classes next week, so enjoy the weekend on this one. Unless you like a [1 minute read](https://teamtreehouse.com/community/innertext-vs-innerhtml)

**Comment by maybuzz** [comment]
Back to textContent
