### ISSUE TITLE
Avoid target="_blank" unless...

### ISSUE THREAD

**Issue by vandijkstef** [maybuzz/web-app-from-scratch-18-19#5]
... you can convince me after [reading this article](https://css-tricks.com/use-target_blank/)

https://github.com/maybuzz/web-app-from-scratch-18-19/blob/98b93decdcb6e5acf420a751d503ee1682e287fa/week1/js/app.js#L14

**Comment by maybuzz** [comment]
Nope can't do. Changed it, thanks!
